# Trigger the workflow on push and pull_request events
on:
  push:
    branches:
      - main  # Trigger on changes to the main branch (or adjust as necessary)
  pull_request:
    branches:
      - main  # Trigger on pull requests targeting the main branch (or adjust as necessary)
 
jobs:
  terraform:
    name: Run Terraform
    runs-on: ubuntu-latest  # Run the job on the latest Ubuntu environment
 
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3
 
      # Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.4.0'  # Specify your desired Terraform version
 
      # Set up AWS Credentials (Securely use GitHub Secrets)
      - name: Set up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws_access_key_id: ${{ ASIASSC4EA4REIWP26L2 }}
          aws_secret_access_key: ${{ ZpUgF4i7O/SE8hRwDhLrdJztk4RW2uXnCpi/iKtc }}
          aws_region: 'us-east-1'  # Specify your AWS region
 
      # Initialize Terraform
      - name: Terraform Init
        run: terraform init
 
      # Run Terraform Plan
      - name: Terraform Plan
        run: terraform plan -out=tfplan
